name: Rush

on: 
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              suffix: ""
              output-suffix: "_linux"
            - os: windows-latest
              suffix: ".exe"
              output-suffix: ""
            - os: macos-latest
              suffix: ""
              output-suffix: "_mac"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: rush 
          path: "target/release/rush${{matrix.suffix}}"
      - run: mv "target/release/rush${{matrix.suffix}}" "target/release/rush${{matrix.suffix}}${{matrix.output-suffix}}"
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "target/release/rush${{matrix.suffix}}${{matrix.output-suffix}}"
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN  }}